
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-02T03:00:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "92c329a5b0cd3b70e69a1ba55d415d2384f54b62",
 "version": "1.1.dev2240"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
