import requests


class DingSDK:
  appkey = ...
  agent_id = ...
  appsecret = ...
  access_token = ...


class DingSDKError(Exception): ...


def get_oapi() -> dict: ...
def post_oapi() -> dict: ...
def get_api() -> dict: ...
def post_api() -> dict: ...
