
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-03T11:18:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "64a0b319bfe6cce3bea1d882e427fa29b170a83b",
 "version": "1.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
