# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('xenorchestra')


class _ExportableConfig(types.ModuleType):
    @property
    def insecure(self) -> Optional[bool]:
        """
        Whether SSL should be verified or not
        """
        return __config__.get_bool('insecure') or _utilities.get_env_bool('XOA_INSECURE')

    @property
    def password(self) -> Optional[str]:
        """
        Password for xoa api
        """
        return __config__.get('password') or _utilities.get_env('XOA_PASSWORD')

    @property
    def url(self) -> Optional[str]:
        """
        Hostname of the xoa router
        """
        return __config__.get('url') or _utilities.get_env('XOA_URL')

    @property
    def username(self) -> Optional[str]:
        """
        User account for xoa api
        """
        return __config__.get('username') or _utilities.get_env('XOA_USER')

