
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-04T08:37:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0387d65c28a3515d237f777fa1c2a3d4bbaf8106",
 "version": "2.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
