# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\.\couchbase_version.py
# at
#    2022-10-07 09:10:07.400086
__version__ = '4.0.5rc1'