
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-04T14:39:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8883dc845c906081d3f1a729c188453fa8887a05",
 "version": "v22.12.00a221006"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
