
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-09T10:37:29+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "285643e121e23bedee4f5e36cfbb62e75fdc7a6d",
 "version": "3.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
