
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-09T15:51:15+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c7bc1ab68359041fa5cc74aeba5040a8917c352",
 "version": "v3.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
