
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-05T20:33:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8b54befc863fb5f38527a7367c11d04767320c0",
 "version": "0.2.30.post0.dev40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
