
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-03T16:21:07-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "54c738ba2e68fe7dd41dac7cbad7223669f7f46d",
 "version": "v0.1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
