
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-07T19:04:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb17c1a50cfb66de4a3737fbfc65f1855479ca7d",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
