# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Antonio\Documents\pyenv\devenv\autologbook\autologbook\ui\mirroring_engine_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from autologbook import resource_rc


class Ui_mirroring_engine_dialog(object):
    def setupUi(self, mirroring_engine_dialog):
        mirroring_engine_dialog.setObjectName("mirroring_engine_dialog")
        mirroring_engine_dialog.resize(355, 72)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ":/resources/icons8-logbook-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mirroring_engine_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(mirroring_engine_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(mirroring_engine_dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(mirroring_engine_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 2, 1)
        self.comboBox = QtWidgets.QComboBox(mirroring_engine_dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label.setBuddy(self.comboBox)

        self.retranslateUi(mirroring_engine_dialog)
        self.buttonBox.accepted.connect(mirroring_engine_dialog.accept)
        self.buttonBox.rejected.connect(mirroring_engine_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(mirroring_engine_dialog)

    def retranslateUi(self, mirroring_engine_dialog):
        _translate = QtCore.QCoreApplication.translate
        mirroring_engine_dialog.setWindowTitle(_translate(
            "mirroring_engine_dialog", "Mirroring engine"))
        self.label.setText(_translate(
            "mirroring_engine_dialog", "Select a mirroring engine"))
        self.comboBox.setItemText(0, _translate(
            "mirroring_engine_dialog", "watchdog"))
        self.comboBox.setItemText(1, _translate(
            "mirroring_engine_dialog", "robocopy"))
