
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T18:09:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3eb3073404171c8394cb7561e775e009eddb501",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
