
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-06T03:30:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6da82973c1bcfdcbc8395c2d4162b9ef547f7df",
 "version": "1.17.1.post0.dev188"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
