
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-06T15:06:21+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "035c57be735b9ec4f51e96a1bf2f0d107b9efd9b",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
