import socket
from ..core.base import LoggingEntity as LoggingEntity
from typing import List

class SocketServer(LoggingEntity):
    def __init__(self, *args, **kwargs) -> None: ...
    def set_config(self, config) -> None: ...
    def set_context(self, context) -> None: ...
    def bind(self, port: int, host: str = ...) -> List[socket.socket]: ...
    def cleanup(self) -> None: ...
