# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/demand_pred_model',
                'doc_host': 'https://f.ghavamian.github.io',
                'git_url': 'https://github.com/f.ghavamian/demand_pred_model',
                'lib_path': 'demand_pred_model'},
  'syms': { 'demand_pred_model.model': { 'demand_pred_model.model.make_model': ('model.html#make_model', 'demand_pred_model/model.py'),
                                         'demand_pred_model.model.predict': ('model.html#predict', 'demand_pred_model/model.py'),
                                         'demand_pred_model.model.train': ('model.html#train', 'demand_pred_model/model.py')}}}