/*!
 @file a.config.h
 @brief algorithm library configuration
 @details it is autogenerated by setup.py
 @copyright Copyright (C) 2020-present tqfx, All rights reserved.
*/

#ifndef __A_CONFIG_H__
#define __A_CONFIG_H__

#define A_VERSION_MAJOR 0
#define A_VERSION_MINOR 1
#define A_VERSION_PATCH 1
#define A_VERSION_TWEAK 202210081832

/*! algorithm library version string */
#define A_VERSION "0.1.1-rc2"

#endif /* __A_CONFIG_H__ */
