VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('04')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('53')
MAJOR_VERSION = 0
MINOR_VERSION = 6
PATCH_VERSION = 202210041253
version_date = '2022/10/04 12:53'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
