
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-01T17:26:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa5007a39ff98c2bed01cbe9317111b6f7224b9d",
 "version": "0.0.120"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
