"""
    Proxy Service

    This is the Insights Engine Proxy Service, the single touch point for accessing the insights engine services.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: eden.trainor@compassdigital.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import insights_engine
from insights_engine.model.delete_filter_output import DeleteFilterOutput


class TestDeleteFilterOutput(unittest.TestCase):
    """DeleteFilterOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteFilterOutput(self):
        """Test DeleteFilterOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteFilterOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
