"""
    Proxy Service

    This is the Insights Engine Proxy Service, the single touch point for accessing the insights engine services.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: eden.trainor@compassdigital.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import insights_engine
from insights_engine.model.insight_payload import InsightPayload
globals()['InsightPayload'] = InsightPayload
from insights_engine.model.get_group_insights_output import GetGroupInsightsOutput


class TestGetGroupInsightsOutput(unittest.TestCase):
    """GetGroupInsightsOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetGroupInsightsOutput(self):
        """Test GetGroupInsightsOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetGroupInsightsOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
