"""
    Proxy Service

    This is the Insights Engine Proxy Service, the single touch point for accessing the insights engine services.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: eden.trainor@compassdigital.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import insights_engine
from insights_engine.api.groups_api import GroupsApi  # noqa: E501


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_members(self):
        """Test case for add_members

        Add members to group  # noqa: E501
        """
        pass

    def test_create_group(self):
        """Test case for create_group

        Create Admin Group  # noqa: E501
        """
        pass

    def test_delete_all_admin_groups(self):
        """Test case for delete_all_admin_groups

        Delete Admin's Groups  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Delete a group  # noqa: E501
        """
        pass

    def test_delete_group_members(self):
        """Test case for delete_group_members

        Delete Group members  # noqa: E501
        """
        pass

    def test_get_all_admin_groups(self):
        """Test case for get_all_admin_groups

        Fetch Admins Groups  # noqa: E501
        """
        pass

    def test_get_group_admins(self):
        """Test case for get_group_admins

        Fetch admins for group name  # noqa: E501
        """
        pass

    def test_get_group_members(self):
        """Test case for get_group_members

        Fetch group members  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
