"""
    Proxy Service

    This is the Insights Engine Proxy Service, the single touch point for accessing the insights engine services.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: eden.trainor@compassdigital.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import insights_engine
from insights_engine.model.permission import Permission
globals()['Permission'] = Permission
from insights_engine.model.update_user_input import UpdateUserInput


class TestUpdateUserInput(unittest.TestCase):
    """UpdateUserInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateUserInput(self):
        """Test UpdateUserInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateUserInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
