
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-05T13:42:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0e8c4efa47900334c11fd51ed0c50bd6e77044c",
 "version": "1.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
