VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('03')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('36')
MAJOR_VERSION = 0
MINOR_VERSION = 15
PATCH_VERSION = 202210030836
version_date = '2022/10/03 08:36'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
