VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('08')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('31')
MAJOR_VERSION = 0
MINOR_VERSION = 18
PATCH_VERSION = 202210081031
version_date = '2022/10/08 10:31'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
