
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-02T03:00:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d682ce5ea77d3ddc5abd97cdeb7dd0df2db97b3",
 "version": "0.4.dev2240"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
