
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-05T15:42:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ede9db218c84434ff8797f138c0f3cd934d3b27",
 "version": "2.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
