from typing import Any

class FatalError(Exception): ...

class UrlError(FatalError):
    uri: Any  # Not actually a URI! :-(
    def __init__(self, uri: Any) -> None: ...

class HttpClientError(FatalError):
    status: int
    uri: str
    def __init__(self, uri: str, status: int) -> None: ...

class HttpNotFoundError(HttpClientError): ...
class StreamNotFoundError(Exception): ...
class RejectedMessageException(Exception): ...
class InvalidDataException(Exception): ...
