VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('06')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('22')
MAJOR_VERSION = 0
MINOR_VERSION = 16
PATCH_VERSION = 202210060922
version_date = '2022/10/06 09:22'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
