
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-04T18:15:33+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "d5e53a2f385bcfe16d6bdd4c9461d46a35307bf9",
 "version": "0.2.2.post0.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
