"""
    Proxy Service

    This is the Insights Engine Proxy Service, the single touch point for accessing the insights engine services.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: eden.trainor@compassdigital.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import insights_engine
from insights_engine.api.subscriptions_api import SubscriptionsApi  # noqa: E501


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_subscription(self):
        """Test case for add_subscription

        Add a subscription for this user  # noqa: E501
        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        deletes a subscription for this user  # noqa: E501
        """
        pass

    def test_get_app_subscriptions(self):
        """Test case for get_app_subscriptions

        Get all subscriptions for app  # noqa: E501
        """
        pass

    def test_get_user_subscriptions(self):
        """Test case for get_user_subscriptions

        Get subscribed windows for this user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
