"""
    Proxy Service

    This is the Insights Engine Proxy Service, the single touch point for accessing the insights engine services.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: eden.trainor@compassdigital.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import insights_engine
from insights_engine.model.user import User
globals()['User'] = User
from insights_engine.model.add_members_input import AddMembersInput


class TestAddMembersInput(unittest.TestCase):
    """AddMembersInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddMembersInput(self):
        """Test AddMembersInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddMembersInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
