# Generated by Django 4.0.5 on 2022-07-04 17:51

from django.db import migrations
import streamfield.field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_page_slug_alter_page_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='stream',
            field=streamfield.field.models.StreamField(default=list, verbose_name='stream'),
        ),
    ]
