# Generated by Django 4.1.1 on 2022-09-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_page_options_page_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='text',
        ),
    ]
