# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"set_logger": "05_util.ipynb",
         "logger": "20-alg.ipynb",
         "suspect": "20-alg.ipynb"}

modules = ["util.py",
           "api.py",
           "alg.py"]

doc_url = "https://Tre-Xanh.github.io/lapros/"

git_url = "https://github.com/Tre-Xanh/lapros/tree/master/"

def custom_doc_links(name): return None
