
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-04T20:05:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "62326376a778c589553d6c219c4254ed4b75557d",
 "version": "2.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
