VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('04')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 0
MINOR_VERSION = 6
PATCH_VERSION = 202210041316
version_date = '2022/10/04 13:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
