# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from summa.proto import query_pb2 as summa_dot_proto_dot_query__pb2
from summa.proto import search_service_pb2 as summa_dot_proto_dot_search__service__pb2


class SearchApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.search = channel.unary_unary(
                '/summa.proto.SearchApi/search',
                request_serializer=summa_dot_proto_dot_search__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=summa_dot_proto_dot_query__pb2.SearchResponse.FromString,
                )


class SearchApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'search': grpc.unary_unary_rpc_method_handler(
                    servicer.search,
                    request_deserializer=summa_dot_proto_dot_search__service__pb2.SearchRequest.FromString,
                    response_serializer=summa_dot_proto_dot_query__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'summa.proto.SearchApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/summa.proto.SearchApi/search',
            summa_dot_proto_dot_search__service__pb2.SearchRequest.SerializeToString,
            summa_dot_proto_dot_query__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
