# coding: utf-8

"""
    Getir-Locals Integration Swagger Documentation

    This documentation is created by Getir Developers for Getir-Locals Integration.For this integration, you need to take CLIENT NAME and CLIENT SECRET keys from Getir-dev team and use these keys for authentication. You also need to use access token provided after successful login to be able to use all other endpoints  You can view information about the active order through /orders/unapproved endpoints. The status of the order is managed via verify, prepare, handover and cancel endpoints. Details on order management are as follows:  For orders to be made by the Getir courier, the flow is as follows:  Supplier confirms order --verify<br />Supplier prepares order --prepare (1-2 minutes must pass before delivery)<br />Supplier hands over the order to Getir courier --handover<br />For Getir delivery, transactions are made by the Getir courier after handover.  A valid reason will be requested from the supplier to cancel an order. Valid reasons may vary depending on the instant status of the order. For this reason, before canceling an order, you have to get instant valid order cancellation reasons from /orders/{orderId}/cancel-options endpoint.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateShopStatusRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'working_status': 'str'
    }

    attribute_map = {
        'working_status': 'workingStatus'
    }

    def __init__(self, working_status=None):  # noqa: E501
        """UpdateShopStatusRequest - a model defined in Swagger"""  # noqa: E501
        self._working_status = None
        self.discriminator = None
        self.working_status = working_status

    @property
    def working_status(self):
        """Gets the working_status of this UpdateShopStatusRequest.  # noqa: E501


        :return: The working_status of this UpdateShopStatusRequest.  # noqa: E501
        :rtype: str
        """
        return self._working_status

    @working_status.setter
    def working_status(self, working_status):
        """Sets the working_status of this UpdateShopStatusRequest.


        :param working_status: The working_status of this UpdateShopStatusRequest.  # noqa: E501
        :type: str
        """
        if working_status is None:
            raise ValueError("Invalid value for `working_status`, must not be `None`")  # noqa: E501
        allowed_values = ["CLOSED", "OPEN"]  # noqa: E501
        if working_status not in allowed_values:
            raise ValueError(
                "Invalid value for `working_status` ({0}), must be one of {1}"  # noqa: E501
                .format(working_status, allowed_values)
            )

        self._working_status = working_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateShopStatusRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateShopStatusRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
