VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('06')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('09')
MAJOR_VERSION = 0
MINOR_VERSION = 17
PATCH_VERSION = 202210061209
version_date = '2022/10/06 12:09'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
