
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-08T00:20:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a714662eb5ed23e979201dcb6e3f2ea35442549f",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
