VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('03')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202210031649
version_date = '2022/10/03 16:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
