# autogenerated
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_source/data_source.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rime_sdk.protos.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from rime_sdk.protos.schema.data_source import data_source_pb2 as schema_dot_data__source_dot_data__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64\x61ta_source/data_source.proto\x12\x04rime\x1a\x1cgoogle/api/annotations.proto\x1a$schema/data_source/data_source.proto\"\x96\x01\n\x17\x43reateDataSourceRequest\x12\x33\n\x0b\x64\x61ta_source\x18\x01 \x01(\x0b\x32\x1e.schema.data_source.DataSource\x12\x34\n\x12\x64\x65lta_lake_secrets\x18\x02 \x01(\x0b\x32\x16.rime.DeltaLakeSecretsH\x00\x42\x10\n\x0esecret_details\"3\n\x10\x44\x65ltaLakeSecrets\x12\x1f\n\x17\x64\x65lta_lake_access_token\x18\x01 \x01(\t\"\x1a\n\x18\x43reateDataSourceResponse\"\x18\n\x16ListDataSourcesRequest\"O\n\x17ListDataSourcesResponse\x12\x34\n\x0c\x64\x61ta_sources\x18\x01 \x03(\x0b\x32\x1e.schema.data_source.DataSource\"\'\n\x17\x44\x65leteDataSourceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x18\x44\x65leteDataSourceResponse2\xe1\x02\n\x11\x44\x61taSourceService\x12n\n\x10\x43reateDataSource\x12\x1d.rime.CreateDataSourceRequest\x1a\x1e.rime.CreateDataSourceResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/data-sources:\x01*\x12h\n\x0fListDataSources\x12\x1c.rime.ListDataSourcesRequest\x1a\x1d.rime.ListDataSourcesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/data-sources\x12r\n\x10\x44\x65leteDataSource\x12\x1d.rime.DeleteDataSourceRequest\x1a\x1e.rime.DeleteDataSourceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/data-sources/{name}B\x1bZ\x19ri/_gen/protos/datasourceb\x06proto3')



_CREATEDATASOURCEREQUEST = DESCRIPTOR.message_types_by_name['CreateDataSourceRequest']
_DELTALAKESECRETS = DESCRIPTOR.message_types_by_name['DeltaLakeSecrets']
_CREATEDATASOURCERESPONSE = DESCRIPTOR.message_types_by_name['CreateDataSourceResponse']
_LISTDATASOURCESREQUEST = DESCRIPTOR.message_types_by_name['ListDataSourcesRequest']
_LISTDATASOURCESRESPONSE = DESCRIPTOR.message_types_by_name['ListDataSourcesResponse']
_DELETEDATASOURCEREQUEST = DESCRIPTOR.message_types_by_name['DeleteDataSourceRequest']
_DELETEDATASOURCERESPONSE = DESCRIPTOR.message_types_by_name['DeleteDataSourceResponse']
CreateDataSourceRequest = _reflection.GeneratedProtocolMessageType('CreateDataSourceRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATASOURCEREQUEST,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.CreateDataSourceRequest)
  })
_sym_db.RegisterMessage(CreateDataSourceRequest)

DeltaLakeSecrets = _reflection.GeneratedProtocolMessageType('DeltaLakeSecrets', (_message.Message,), {
  'DESCRIPTOR' : _DELTALAKESECRETS,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.DeltaLakeSecrets)
  })
_sym_db.RegisterMessage(DeltaLakeSecrets)

CreateDataSourceResponse = _reflection.GeneratedProtocolMessageType('CreateDataSourceResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATASOURCERESPONSE,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.CreateDataSourceResponse)
  })
_sym_db.RegisterMessage(CreateDataSourceResponse)

ListDataSourcesRequest = _reflection.GeneratedProtocolMessageType('ListDataSourcesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTDATASOURCESREQUEST,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.ListDataSourcesRequest)
  })
_sym_db.RegisterMessage(ListDataSourcesRequest)

ListDataSourcesResponse = _reflection.GeneratedProtocolMessageType('ListDataSourcesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTDATASOURCESRESPONSE,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.ListDataSourcesResponse)
  })
_sym_db.RegisterMessage(ListDataSourcesResponse)

DeleteDataSourceRequest = _reflection.GeneratedProtocolMessageType('DeleteDataSourceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDATASOURCEREQUEST,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.DeleteDataSourceRequest)
  })
_sym_db.RegisterMessage(DeleteDataSourceRequest)

DeleteDataSourceResponse = _reflection.GeneratedProtocolMessageType('DeleteDataSourceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDATASOURCERESPONSE,
  '__module__' : 'rime_sdk.protos.data_source.data_source_pb2'
  # @@protoc_insertion_point(class_scope:rime.DeleteDataSourceResponse)
  })
_sym_db.RegisterMessage(DeleteDataSourceResponse)

_DATASOURCESERVICE = DESCRIPTOR.services_by_name['DataSourceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031ri/_gen/protos/datasource'
  _DATASOURCESERVICE.methods_by_name['CreateDataSource']._options = None
  _DATASOURCESERVICE.methods_by_name['CreateDataSource']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/data-sources:\001*'
  _DATASOURCESERVICE.methods_by_name['ListDataSources']._options = None
  _DATASOURCESERVICE.methods_by_name['ListDataSources']._serialized_options = b'\202\323\344\223\002\022\022\020/v1/data-sources'
  _DATASOURCESERVICE.methods_by_name['DeleteDataSource']._options = None
  _DATASOURCESERVICE.methods_by_name['DeleteDataSource']._serialized_options = b'\202\323\344\223\002\031*\027/v1/data-sources/{name}'
  _CREATEDATASOURCEREQUEST._serialized_start=108
  _CREATEDATASOURCEREQUEST._serialized_end=258
  _DELTALAKESECRETS._serialized_start=260
  _DELTALAKESECRETS._serialized_end=311
  _CREATEDATASOURCERESPONSE._serialized_start=313
  _CREATEDATASOURCERESPONSE._serialized_end=339
  _LISTDATASOURCESREQUEST._serialized_start=341
  _LISTDATASOURCESREQUEST._serialized_end=365
  _LISTDATASOURCESRESPONSE._serialized_start=367
  _LISTDATASOURCESRESPONSE._serialized_end=446
  _DELETEDATASOURCEREQUEST._serialized_start=448
  _DELETEDATASOURCEREQUEST._serialized_end=487
  _DELETEDATASOURCERESPONSE._serialized_start=489
  _DELETEDATASOURCERESPONSE._serialized_end=515
  _DATASOURCESERVICE._serialized_start=518
  _DATASOURCESERVICE._serialized_end=871
# @@protoc_insertion_point(module_scope)
