VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('04')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('07')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202210041607
version_date = '2022/10/04 16:07'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
