
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-15T12:23:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e4e1c033ca414d35af243077dfd26bdb195d9ee",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
