VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('03')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 0
MINOR_VERSION = 15
PATCH_VERSION = 202210031300
version_date = '2022/10/03 13:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
