
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-04T18:12:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "46ae0c8af57c8fb045d4dcacb1a591e32b660204",
 "version": "2.2.1rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
