
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-06T16:06:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3fa39819a7fbd83d31459c9e4d369d6e791bc7a",
 "version": "2022.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
