
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-05T00:57:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffd14a2ebbde484a1e76bbaea78233dba117aee7",
 "version": "v1.2.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
