# Generated by Django 4.1.1 on 2022-09-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_quoteblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerblock',
            options={'verbose_name': 'Header'},
        ),
        migrations.AlterModelOptions(
            name='imageblock',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='quoteblock',
            options={'verbose_name': 'Quote'},
        ),
        migrations.AlterModelOptions(
            name='textblock',
            options={'verbose_name': 'Text'},
        ),
        migrations.AlterField(
            model_name='headerblock',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
