
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-06T16:32:39+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "da138502294c0cdb7d7b015934e2236e43e7e865",
 "version": "v0.6.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
