# coding: utf-8

"""
    Getir-Locals Integration Swagger Documentation

    This documentation is created by Getir Developers for Getir-Locals Integration.For this integration, you need to take CLIENT NAME and CLIENT SECRET keys from Getir-dev team and use these keys for authentication. You also need to use access token provided after successful login to be able to use all other endpoints  You can view information about the active order through /orders/unapproved endpoints. The status of the order is managed via verify, prepare, handover and cancel endpoints. Details on order management are as follows:  For orders to be made by the Getir courier, the flow is as follows:  Supplier confirms order --verify<br />Supplier prepares order --prepare (1-2 minutes must pass before delivery)<br />Supplier hands over the order to Getir courier --handover<br />For Getir delivery, transactions are made by the Getir courier after handover.  A valid reason will be requested from the supplier to cancel an order. Valid reasons may vary depending on the instant status of the order. For this reason, before canceling an order, you have to get instant valid order cancellation reasons from /orders/{orderId}/cancel-options endpoint.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MenuOptionsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'option_id': 'str',
        'status': 'float',
        'amount': 'float',
        'price': 'float'
    }

    attribute_map = {
        'option_id': 'optionId',
        'status': 'status',
        'amount': 'amount',
        'price': 'price'
    }

    def __init__(self, option_id=None, status=None, amount=None, price=None):  # noqa: E501
        """MenuOptionsResponse - a model defined in Swagger"""  # noqa: E501
        self._option_id = None
        self._status = None
        self._amount = None
        self._price = None
        self.discriminator = None
        if option_id is not None:
            self.option_id = option_id
        if status is not None:
            self.status = status
        if amount is not None:
            self.amount = amount
        if price is not None:
            self.price = price

    @property
    def option_id(self):
        """Gets the option_id of this MenuOptionsResponse.  # noqa: E501


        :return: The option_id of this MenuOptionsResponse.  # noqa: E501
        :rtype: str
        """
        return self._option_id

    @option_id.setter
    def option_id(self, option_id):
        """Sets the option_id of this MenuOptionsResponse.


        :param option_id: The option_id of this MenuOptionsResponse.  # noqa: E501
        :type: str
        """

        self._option_id = option_id

    @property
    def status(self):
        """Gets the status of this MenuOptionsResponse.  # noqa: E501


        :return: The status of this MenuOptionsResponse.  # noqa: E501
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MenuOptionsResponse.


        :param status: The status of this MenuOptionsResponse.  # noqa: E501
        :type: float
        """

        self._status = status

    @property
    def amount(self):
        """Gets the amount of this MenuOptionsResponse.  # noqa: E501


        :return: The amount of this MenuOptionsResponse.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this MenuOptionsResponse.


        :param amount: The amount of this MenuOptionsResponse.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def price(self):
        """Gets the price of this MenuOptionsResponse.  # noqa: E501


        :return: The price of this MenuOptionsResponse.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this MenuOptionsResponse.


        :param price: The price of this MenuOptionsResponse.  # noqa: E501
        :type: float
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MenuOptionsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MenuOptionsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
