
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-07T10:39:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e8c91154b6ddb709706802c0d60624398d82956",
 "version": "4.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
